export enum IOChanel {
  MAIN_CONNECTION = "connection",
  DISCONECTION_CHANEL = 'disconnect',
  CHAT_CHANEL = "CHAT_CHANEL",
  GAME_CHANEL = "GAME_CHANEL",
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  ERROR_CHANEL = "ERROR_CHANEL",
  VIEWER_CHANEL = "VIEWER_CHANEL",
  JOIN_CHAT = "JOIN_CHAT",
  CHAT_CHANEL_RECEIVE = "CHAT_CHANEL_RECEIVE",
  CHAT_CHANEL_SEND = "CHAT_CHANEL_SEND",
  GAME_CHANEL_WINNER = "GAME_CHANEL_WINNER",
  
}